# Generated by Django 3.0.3 on 2020-02-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=9, max_digits=10)),
                ('img', models.CharField(max_length=1400)),
            ],
        ),
    ]
